## PARA EJECUTAR USAR EL COMANDO
## include Assigment.run;

#RESET THE AMPL ENVIROMENT
reset;

#LOAD THE MODEL
model Assigment.mod; # versión 2

#LOAD .dat
data Assigment.dat;

#CHANGE THE SOLVER
option solver cplexamp;
#option cplex_options 'sensitivity';

#SAVE SOLUTION
#write bcoalrun;  #usado para soluciones ampl
#write mcoalrun;  #save to MPS format

#SOLVE
solve;

#SHOW RESULT
display  z, x  ;