## PARA EJECUTAR USAR EL COMANDO
## include MCNFP.run;

#RESET THE AMPL ENVIROMENT
reset;

#LOAD THE MODEL
model MCNFP.mod;

#LOAD .dat
#data  EXAM20.dat;
data  MCNFP.dat;

#CHANGE THE SOLVER
option solver cplexamp;

solve;

display z ;
display x ;
display pi, alfa;

#x :=
#1 2   2
#1 3   2
#2 3   2
#2 4   0
#3 4   4
#;

#pi [*] :=
#1   4
#2   2
#3   0
#4  -1
#;

#alfa :=
#1 2    0
#1 3   -2
#2 3   -1
#2 4    0
#3 4    0
#;