## PARA EJECUTAR USAR EL COMANDO
## include UFL.run;

#RESET THE AMPL ENVIROMENT
reset;

#LOAD THE MODEL
#model UFL.mod; # versión 1
model UFL2.mod; # versión 2

#LOAD .dat
data UFL2.dat;

#CHANGE THE SOLVER
option solver cplexamp;
#option cplex_options 'sensitivity';

#SAVE SOLUTION
#write bcoalrun;  #usado para soluciones ampl
#write mcoalrun;  #save to MPS format

#SOLVE
solve;

#SHOW RESULT
display   x , y ;